# 1Dice

In [1]:
arr = [0]*401
arr[0] = 1
arr[1] = 1/6*arr[0]
arr[2] = 1/6*arr[0]+1/6*arr[1]
arr[3] = 1/6*arr[0]+1/6*arr[1]+1/6*arr[2]
arr[4] = 1/6*arr[0]+1/6*arr[1]+1/6*arr[2]+1/6*arr[3]
arr[5] = 1/6*arr[0]+1/6*arr[1]+1/6*arr[2]+1/6*arr[3]+1/6*arr[4]
arr[6] = 1/6*arr[0]+1/6*arr[1]+1/6*arr[2]+1/6*arr[3]+1/6*arr[4]+1/6*arr[5]

In [2]:
for i in range(7,401):
    arr[i] = 1/6*arr[i-6]+1/6*arr[i-5]+1/6*arr[i-4]+1/6*arr[i-3]+1/6*arr[i-2]+1/6*arr[i-1]

In [3]:
arr

[1,
 0.16666666666666666,
 0.19444444444444442,
 0.2268518518518518,
 0.26466049382716045,
 0.3087705761316872,
 0.3602323388203017,
 0.253604395290352,
 0.2680940167276329,
 0.28036894544149765,
 0.28928846103977196,
 0.29339312224187386,
 0.29083021326023833,
 0.2792631923335611,
 0.28353965850742924,
 0.28611393213739533,
 0.2870714299200449,
 0.28670192473342376,
 0.28558672514868205,
 0.2847128104634227,
 0.285621080151733,
 0.2859679837591169,
 0.2859436590294039,
 0.28575569721429706,
 0.2855979926277759,
 0.28559987054095826,
 0.28574771388721415,
 0.2857688195097943,
 0.28573562546824055,
 0.28570095320804667,
 0.285691829207005,
 0.28570746863687646,
 0.28572540165286286,
 0.2857216829471376,
 0.28571382685336155,
 0.2857101937508817,
 0.2857117338413542,
 0.28571505128041236,
 0.28571631505433503,
 0.2857148006212471,
 0.285713653566932,
 0.28571362468586037,
 0.28571419650835683,
 0.2857146069528573,
 0.28571453289826476,
 0.28571423587225303,
 0.2857141417474207,
 0.2857142231108355,
 0.28571432284833137,
 0.28571434390499373,
 0.28571430006368315,
 0.28571426125791954,
 0.28571426548886397,
 0.2857142861124378,
 0.2857142966127049,
 0.28571429224010053,
 0.28571428362928497,
 0.2857142808902186,
 0.2857142841622684,
 0.28571428727450254,
 0.28571428746817995,
 0.2857142859440925,
 0.2857142848947578,
 0.28571428510567,
 0.2857142858082452,
 0.28571428608257465,
 0.28571428588392,
 0.28571428561987666,
 0.2857142855658407,
 0.28571428567768786,
 0.2857142857730242,
 0.285714285767154,
 0.2857142857145839,
 0.2857142856863612,
 0.28571428569744195,
 0.2857142857193755,
 0.28571428572632346,
 0.28571428571854,
 0.28571428571043767,
 0.2857142857097466,
 0.28571428571364416,
 0.28571428571634455,
 0.28571428571583946,
 0.2857142857140921,
 0.2857142857133507,
 0.2857142857138362,
 0.28571428571451785,
 0.2857142857146635,
 0.2857142857143833,
 0.2857142857141406,
 0.28571428571414864,
 0.2857142857142817,
 0.28571428571435586,
 0.28571428571432894,
 0.28571428571427315,
 0.2857142857142548,
 0.2857142857142738,
 0.28571428571429464,
 0.28571428571429686,
 0.28571428571428703,
 0.28571428571428004,
 0.28571428571428115,
 0.2857142857142856,
 0.28571428571428753,
 0.28571428571428636,
 0.2857142857142846,
 0.2857142857142842,
 0.2857142857142849,
 0.28571428571428553,
 0.2857142857142855,
 0.28571428571428514,
 0.2857142857142849,
 0.28571428571428503,
 0.28571428571428514,
 0.2857142857142852,
 0.28571428571428514,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851,
 0.2857142857142851]

# 2 Dices

In [4]:
p = [0,0,1/36,2/36,3/36,4/36,5/36,6/36,5/36,4/36,3/36,2/36,1/36]

In [5]:
prob = [0]*401
prob[0] = 1
for i in range(2,401):
    for j in range(2,13):
        if i-j>=0:
            prob[i] += prob[i-j]*p[j]
prob

[1,
 0,
 0.027777777777777776,
 0.05555555555555555,
 0.08410493827160494,
 0.11419753086419752,
 0.1466263717421125,
 0.18222736625514402,
 0.16634575998323425,
 0.1555260249961896,
 0.14778379568769157,
 0.1412753139871124,
 0.1341994411516577,
 0.1247035753233896,
 0.13856733998588355,
 0.14577135028207475,
 0.14835462718374348,
 0.147889983414447,
 0.14567233892514955,
 0.1428862746109749,
 0.14076409441802093,
 0.14074487228671537,
 0.1415582938895622,
 0.14250305429015225,
 0.1432431712243469,
 0.14364991042099634,
 0.1436704811322487,
 0.14320718896912424,
 0.1427636088138357,
 0.14252805073292954,
 0.14251476065809163,
 0.1426518018490057,
 0.14283608629365713,
 0.14297143339436388,
 0.14300286989638114,
 0.1429593599468104,
 0.14288901516830277,
 0.1428299568556591,
 0.14280152812847288,
 0.14280577338958225,
 0.14283223633606412,
 0.14286064638171203,
 0.14287767046505823,
 0.14287997169343272,
 0.14287156183254465,
 0.14285959252252092,
 0.14285052854219885,
 0.1428475612045912,
 0.14284984180494054,
 0.14285450097162256,
 0.14285870225061367,
 0.14286080670850523,
 0.14286060857511892,
 0.14285894919320613,
 0.1428570616953707,
 0.1428558540076946,
 0.1428556198908671,
 0.14285613087842514,
 0.14285691345548834,
 0.1428575324209942,
 0.14285776874337364,
 0.14285764937795234,
 0.1428573491002414,
 0.14285706110959115,
 0.14285690677363871,
 0.14285690816160976,
 0.1428570120061859,
 0.14285713786500717,
 0.14285722306312873,
 0.14285724418116133,
 0.14285721376456928,
 0.14285716259354403,
 0.14285712013565152,
 0.14285710208585126,
 0.14285710806012464,
 0.14285712724922556,
 0.14285714674482944,
 0.14285715790700262,
 0.14285715867999058,
 0.142857152255243,
 0.1428571438975753,
 0.1428571379273672,
 0.14285713614717177,
 0.14285713791170074,
 0.14285714124350973,
 0.14285714415007536,
 0.14285714550161827,
 0.1428571452344234,
 0.1428571440163005,
 0.14285714270453637,
 0.14285714190573853,
 0.14285714179550002,
 0.1428571421880035,
 0.14285714274024564,
 0.14285714315588618,
 0.14285714329927018,
 0.14285714320016693,
 0.14285714298444974,
 0.1428571427862936,
 0.14285714268656877,
 0.14285714269550792,
 0.1428571427722388,
 0.14285714286008178,
 0.14285714291676457,
 0.14285714292804427,
 0.14285714290441742,
 0.1428571428681089,
 0.14285714283934275,
 0.1428571428281594,
 0.14285714283347975,
 0.14285714284736026,
 0.1428571428608074,
 0.14285714286807577,
 0.1428571428680815,
 0.1428571428632917,
 0.14285714285743628,
 0.1428571428534435,
 0.14285714285242962,
 0.1428571428538259,
 0.1428571428562009,
 0.14285714285818102,
 0.14285714285903275,
 0.14285714285876672,
 0.14285714285787948,
 0.14285714285697118,
 0.142857142856447,
 0.14285714285640594,
 0.14285714285670176,
 0.1428571428570903,
 0.14285714285736967,
 0.14285714285745468,
 0.14285714285737408,
 0.14285714285721957,
 0.14285714285708392,
 0.14285714285702025,
 0.1428571428570319,
 0.14285714285708823,
 0.1428571428571493,
 0.14285714285718676,
 0.14285714285719223,
 0.14285714285717416,
 0.1428571428571485,
 0.1428571428571291,
 0.1428571428571223,
 0.14285714285712675,
 0.14285714285713677,
 0.14285714285714604,
 0.1428571428571507,
 0.14285714285715034,
 0.14285714285714682,
 0.1428571428571427,
 0.14285714285714007,
 0.1428571428571395,
 0.14285714285714057,
 0.1428571428571423,
 0.14285714285714363,
 0.14285714285714415,
 0.1428571428571439,
 0.1428571428571433,
 0.14285714285714263,
 0.1428571428571423,
 0.1428571428571423,
 0.1428571428571425,
 0.1428571428571428,
 0.14285714285714296,
 0.14285714285714302,
 0.14285714285714296,
 0.14285714285714285,
 0.14285714285714277,
 0.14285714285714274,
 0.14285714285714274,
 0.14285714285714274,
 0.1428571428571428,
 0.14285714285714282,
 0.14285714285714282,
 0.14285714285714282,
 0.1428571428571428,
 0.1428571428571428,
 0.1428571428571428,
 0.1428571428571428,
 0.1428571428571428,
 0.1428571428571428,
 0.1428571428571428,
 0.1428571428571428,
 0.1428571428571428,
 0.1428571428571428,
 0.1428571428571428,
 0.1428571428571428,
 0.1428571428571428,
 0.1428571428571428,
 0.1428571428571428,
 0.1428571428571428,
 0.1428571428571428,
 0.1428571428571428,
 0.1428571428571428,
 0.1428571428571428,
 0.1428571428571428,
 0.1428571428571428,
 0.1428571428571428,
 0.1428571428571428,
 0.1428571428571428,
 0.1428571428571428,
 0.1428571428571428,
 0.1428571428571428,
 0.1428571428571428,
 0.1428571428571428,
 0.1428571428571428,
 0.1428571428571428,
 0.1428571428571428,
 0.1428571428571428,
 0.1428571428571428,
 0.1428571428571428,
 0.1428571428571428,
 0.1428571428571428,
 0.1428571428571428,
 0.1428571428571428,
 0.1428571428571428,
 0.1428571428571428,
 0.1428571428571428,
 0.1428571428571428,
 0.1428571428571428,
 0.1428571428571428,
 0.1428571428571428,
 0.1428571428571428,
 0.1428571428571428,
 0.1428571428571428,
 0.1428571428571428,
 0.1428571428571428,
 0.1428571428571428,
 0.1428571428571428,
 0.1428571428571428,
 0.1428571428571428,
 0.1428571428571428,
 0.1428571428571428,
 0.1428571428571428,
 0.1428571428571428,
 0.1428571428571428,
 0.1428571428571428,
 0.1428571428571428,
 0.1428571428571428,
 0.1428571428571428,
 0.1428571428571428,
 0.1428571428571428,
 0.1428571428571428,
 0.1428571428571428,
 0.1428571428571428,
 0.1428571428571428,
 0.1428571428571428,
 0.1428571428571428,
 0.1428571428571428,
 0.1428571428571428,
 0.1428571428571428,
 0.1428571428571428,
 0.1428571428571428,
 0.1428571428571428,
 0.1428571428571428,
 0.1428571428571428,
 0.1428571428571428,
 0.1428571428571428,
 0.1428571428571428,
 0.1428571428571428,
 0.1428571428571428,
 0.1428571428571428,
 0.1428571428571428,
 0.1428571428571428,
 0.1428571428571428,
 0.1428571428571428,
 0.1428571428571428,
 0.1428571428571428,
 0.1428571428571428,
 0.1428571428571428,
 0.1428571428571428,
 0.1428571428571428,
 0.1428571428571428,
 0.1428571428571428,
 0.1428571428571428,
 0.1428571428571428,
 0.1428571428571428,
 0.1428571428571428,
 0.1428571428571428,
 0.1428571428571428,
 0.1428571428571428,
 0.1428571428571428,
 0.1428571428571428,
 0.1428571428571428,
 0.1428571428571428,
 0.1428571428571428,
 0.1428571428571428,
 0.1428571428571428,
 0.1428571428571428,
 0.1428571428571428,
 0.1428571428571428,
 0.1428571428571428,
 0.1428571428571428,
 0.1428571428571428,
 0.1428571428571428,
 0.1428571428571428,
 0.1428571428571428,
 0.1428571428571428,
 0.1428571428571428,
 0.1428571428571428,
 0.1428571428571428,
 0.1428571428571428,
 0.1428571428571428,
 0.1428571428571428,
 0.1428571428571428,
 0.1428571428571428,
 0.1428571428571428,
 0.1428571428571428,
 0.1428571428571428,
 0.1428571428571428,
 0.1428571428571428,
 0.1428571428571428,
 0.1428571428571428,
 0.1428571428571428,
 0.1428571428571428,
 0.1428571428571428,
 0.1428571428571428,
 0.1428571428571428,
 0.1428571428571428,
 0.1428571428571428,
 0.1428571428571428,
 0.1428571428571428,
 0.1428571428571428,
 0.1428571428571428,
 0.1428571428571428,
 0.1428571428571428,
 0.1428571428571428,
 0.1428571428571428,
 0.1428571428571428,
 0.1428571428571428,
 0.1428571428571428,
 0.1428571428571428,
 0.1428571428571428,
 0.1428571428571428,
 0.1428571428571428,
 0.1428571428571428,
 0.1428571428571428,
 0.1428571428571428,
 0.1428571428571428,
 0.1428571428571428,
 0.1428571428571428,
 0.1428571428571428,
 0.1428571428571428,
 0.1428571428571428,
 0.1428571428571428,
 0.1428571428571428,
 0.1428571428571428,
 0.1428571428571428,
 0.1428571428571428,
 0.1428571428571428,
 0.1428571428571428,
 0.1428571428571428,
 0.1428571428571428,
 0.1428571428571428,
 0.1428571428571428,
 0.1428571428571428,
 0.1428571428571428,
 0.1428571428571428,
 0.1428571428571428,
 0.1428571428571428,
 0.1428571428571428,
 0.1428571428571428,
 0.1428571428571428,
 0.1428571428571428,
 0.1428571428571428,
 0.1428571428571428,
 0.1428571428571428,
 0.1428571428571428,
 0.1428571428571428,
 0.1428571428571428,
 0.1428571428571428,
 0.1428571428571428,
 0.1428571428571428,
 0.1428571428571428,
 0.1428571428571428,
 0.1428571428571428,
 0.1428571428571428,
 0.1428571428571428,
 0.1428571428571428,
 0.1428571428571428,
 0.1428571428571428,
 0.1428571428571428,
 0.1428571428571428,
 0.1428571428571428,
 0.1428571428571428,
 0.1428571428571428,
 0.1428571428571428,
 0.1428571428571428,
 0.1428571428571428,
 0.1428571428571428,
 0.1428571428571428,
 0.1428571428571428,
 0.1428571428571428,
 0.1428571428571428,
 0.1428571428571428,
 0.1428571428571428,
 0.1428571428571428,
 0.1428571428571428,
 0.1428571428571428,
 0.1428571428571428]

In [6]:
prob[400]

0.1428571428571428

# Time Summary

In [7]:
import pandas as pd
df = pd.read_csv('time.csv',index_col=0)
df = df.dropna()
df

        timestamp
user_id
621.0     0:00:02
818.0     0:00:10
4.0       0:00:21
563.0     0:00:21
671.0     0:00:26
...           ...
12.0     23:59:18
646.0    23:59:20
458.0    23:59:34
968.0    23:59:53
775.0    23:59:59

[61582 rows x 1 columns]

In [8]:
def get_hour(row):
    if row['timestamp'][1]==':': 
        return row['timestamp'][0]
    else:
        return row['timestamp'][:2]

In [9]:
df['hour'] = df.apply(lambda row: get_hour(row),axis=1)
df

        timestamp hour
user_id
621.0     0:00:02    0
818.0     0:00:10    0
4.0       0:00:21    0
563.0     0:00:21    0
671.0     0:00:26    0
...           ...  ...
12.0     23:59:18   23
646.0    23:59:20   23
458.0    23:59:34   23
968.0    23:59:53   23
775.0    23:59:59   23

[61582 rows x 2 columns]

In [10]:
df.groupby('hour').count()

      timestamp
hour
0          2747
1          2651
10         2509
11         2481
12         2793
13         2890
14         2907
15         2672
16         2144
17         2208
18         2276
19         2356
2          2751
20         2560
21         2638
22         2539
23         2596
3          2509
4          2628
5          2560
6          2509
7          2616
8          2575
9          2467

In [11]:
count_list = df.groupby('hour').count().timestamp.tolist()
max(count_list)-min(count_list)

763